version: "3"

services:
  app:
    container_name: "controle-despensa"
    build: .
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
      - ./usr/app/node_modules
